name: HEXO CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Configure Git and SSH
        env:
          HEXO_DEPLOY_PRI: ${{ secrets.HEXO_DEPLOY_PRI }}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Wh1teJ0ker"
          git config --global user.email "1430100306@qq.com"

      - name: Set npm registry and upgrade
        run: |
          npm config set registry https://registry.npmjs.org/
          npm install -g npm@latest

      - name: Install Hexo and dependencies
        run: |
          npx hexo --version || echo "Installing hexo-cli..."
          npm install --legacy-peer-deps || npm install --legacy-peer-deps --force

      - name: Deploy Hexo
        run: |
          npx hexo clean
          npx hexo generate
          npx hexo deploy
